/* Copyright 2013 Jukka Pirinen

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

package org.pirinen.c64dslj.builder;

public class ByteHex implements DataType<Byte> {

	public static final ByteHex $00 = new ByteHex(0);
	public static final ByteHex $01 = new ByteHex(1);
	public static final ByteHex $02 = new ByteHex(2);
	public static final ByteHex $03 = new ByteHex(3);
	public static final ByteHex $04 = new ByteHex(4);
	public static final ByteHex $05 = new ByteHex(5);
	public static final ByteHex $06 = new ByteHex(6);
	public static final ByteHex $07 = new ByteHex(7);
	public static final ByteHex $08 = new ByteHex(8);
	public static final ByteHex $09 = new ByteHex(9);
	public static final ByteHex $0a = new ByteHex(10);
	public static final ByteHex $0b = new ByteHex(11);
	public static final ByteHex $0c = new ByteHex(12);
	public static final ByteHex $0d = new ByteHex(13);
	public static final ByteHex $0e = new ByteHex(14);
	public static final ByteHex $0f = new ByteHex(15);
	public static final ByteHex $10 = new ByteHex(16);
	public static final ByteHex $11 = new ByteHex(17);
	public static final ByteHex $12 = new ByteHex(18);
	public static final ByteHex $13 = new ByteHex(19);
	public static final ByteHex $14 = new ByteHex(20);
	public static final ByteHex $15 = new ByteHex(21);
	public static final ByteHex $16 = new ByteHex(22);
	public static final ByteHex $17 = new ByteHex(23);
	public static final ByteHex $18 = new ByteHex(24);
	public static final ByteHex $19 = new ByteHex(25);
	public static final ByteHex $1a = new ByteHex(26);
	public static final ByteHex $1b = new ByteHex(27);
	public static final ByteHex $1c = new ByteHex(28);
	public static final ByteHex $1d = new ByteHex(29);
	public static final ByteHex $1e = new ByteHex(30);
	public static final ByteHex $1f = new ByteHex(31);
	public static final ByteHex $20 = new ByteHex(32);
	public static final ByteHex $21 = new ByteHex(33);
	public static final ByteHex $22 = new ByteHex(34);
	public static final ByteHex $23 = new ByteHex(35);
	public static final ByteHex $24 = new ByteHex(36);
	public static final ByteHex $25 = new ByteHex(37);
	public static final ByteHex $26 = new ByteHex(38);
	public static final ByteHex $27 = new ByteHex(39);
	public static final ByteHex $28 = new ByteHex(40);
	public static final ByteHex $29 = new ByteHex(41);
	public static final ByteHex $2a = new ByteHex(42);
	public static final ByteHex $2b = new ByteHex(43);
	public static final ByteHex $2c = new ByteHex(44);
	public static final ByteHex $2d = new ByteHex(45);
	public static final ByteHex $2e = new ByteHex(46);
	public static final ByteHex $2f = new ByteHex(47);
	public static final ByteHex $30 = new ByteHex(48);
	public static final ByteHex $31 = new ByteHex(49);
	public static final ByteHex $32 = new ByteHex(50);
	public static final ByteHex $33 = new ByteHex(51);
	public static final ByteHex $34 = new ByteHex(52);
	public static final ByteHex $35 = new ByteHex(53);
	public static final ByteHex $36 = new ByteHex(54);
	public static final ByteHex $37 = new ByteHex(55);
	public static final ByteHex $38 = new ByteHex(56);
	public static final ByteHex $39 = new ByteHex(57);
	public static final ByteHex $3a = new ByteHex(58);
	public static final ByteHex $3b = new ByteHex(59);
	public static final ByteHex $3c = new ByteHex(60);
	public static final ByteHex $3d = new ByteHex(61);
	public static final ByteHex $3e = new ByteHex(62);
	public static final ByteHex $3f = new ByteHex(63);
	public static final ByteHex $40 = new ByteHex(64);
	public static final ByteHex $41 = new ByteHex(65);
	public static final ByteHex $42 = new ByteHex(66);
	public static final ByteHex $43 = new ByteHex(67);
	public static final ByteHex $44 = new ByteHex(68);
	public static final ByteHex $45 = new ByteHex(69);
	public static final ByteHex $46 = new ByteHex(70);
	public static final ByteHex $47 = new ByteHex(71);
	public static final ByteHex $48 = new ByteHex(72);
	public static final ByteHex $49 = new ByteHex(73);
	public static final ByteHex $4a = new ByteHex(74);
	public static final ByteHex $4b = new ByteHex(75);
	public static final ByteHex $4c = new ByteHex(76);
	public static final ByteHex $4d = new ByteHex(77);
	public static final ByteHex $4e = new ByteHex(78);
	public static final ByteHex $4f = new ByteHex(79);
	public static final ByteHex $50 = new ByteHex(80);
	public static final ByteHex $51 = new ByteHex(81);
	public static final ByteHex $52 = new ByteHex(82);
	public static final ByteHex $53 = new ByteHex(83);
	public static final ByteHex $54 = new ByteHex(84);
	public static final ByteHex $55 = new ByteHex(85);
	public static final ByteHex $56 = new ByteHex(86);
	public static final ByteHex $57 = new ByteHex(87);
	public static final ByteHex $58 = new ByteHex(88);
	public static final ByteHex $59 = new ByteHex(89);
	public static final ByteHex $5a = new ByteHex(90);
	public static final ByteHex $5b = new ByteHex(91);
	public static final ByteHex $5c = new ByteHex(92);
	public static final ByteHex $5d = new ByteHex(93);
	public static final ByteHex $5e = new ByteHex(94);
	public static final ByteHex $5f = new ByteHex(95);
	public static final ByteHex $60 = new ByteHex(96);
	public static final ByteHex $61 = new ByteHex(97);
	public static final ByteHex $62 = new ByteHex(98);
	public static final ByteHex $63 = new ByteHex(99);
	public static final ByteHex $64 = new ByteHex(100);
	public static final ByteHex $65 = new ByteHex(101);
	public static final ByteHex $66 = new ByteHex(102);
	public static final ByteHex $67 = new ByteHex(103);
	public static final ByteHex $68 = new ByteHex(104);
	public static final ByteHex $69 = new ByteHex(105);
	public static final ByteHex $6a = new ByteHex(106);
	public static final ByteHex $6b = new ByteHex(107);
	public static final ByteHex $6c = new ByteHex(108);
	public static final ByteHex $6d = new ByteHex(109);
	public static final ByteHex $6e = new ByteHex(110);
	public static final ByteHex $6f = new ByteHex(111);
	public static final ByteHex $70 = new ByteHex(112);
	public static final ByteHex $71 = new ByteHex(113);
	public static final ByteHex $72 = new ByteHex(114);
	public static final ByteHex $73 = new ByteHex(115);
	public static final ByteHex $74 = new ByteHex(116);
	public static final ByteHex $75 = new ByteHex(117);
	public static final ByteHex $76 = new ByteHex(118);
	public static final ByteHex $77 = new ByteHex(119);
	public static final ByteHex $78 = new ByteHex(120);
	public static final ByteHex $79 = new ByteHex(121);
	public static final ByteHex $7a = new ByteHex(122);
	public static final ByteHex $7b = new ByteHex(123);
	public static final ByteHex $7c = new ByteHex(124);
	public static final ByteHex $7d = new ByteHex(125);
	public static final ByteHex $7e = new ByteHex(126);
	public static final ByteHex $7f = new ByteHex(127);
	public static final ByteHex $80 = new ByteHex(128);
	public static final ByteHex $81 = new ByteHex(129);
	public static final ByteHex $82 = new ByteHex(130);
	public static final ByteHex $83 = new ByteHex(131);
	public static final ByteHex $84 = new ByteHex(132);
	public static final ByteHex $85 = new ByteHex(133);
	public static final ByteHex $86 = new ByteHex(134);
	public static final ByteHex $87 = new ByteHex(135);
	public static final ByteHex $88 = new ByteHex(136);
	public static final ByteHex $89 = new ByteHex(137);
	public static final ByteHex $8a = new ByteHex(138);
	public static final ByteHex $8b = new ByteHex(139);
	public static final ByteHex $8c = new ByteHex(140);
	public static final ByteHex $8d = new ByteHex(141);
	public static final ByteHex $8e = new ByteHex(142);
	public static final ByteHex $8f = new ByteHex(143);
	public static final ByteHex $90 = new ByteHex(144);
	public static final ByteHex $91 = new ByteHex(145);
	public static final ByteHex $92 = new ByteHex(146);
	public static final ByteHex $93 = new ByteHex(147);
	public static final ByteHex $94 = new ByteHex(148);
	public static final ByteHex $95 = new ByteHex(149);
	public static final ByteHex $96 = new ByteHex(150);
	public static final ByteHex $97 = new ByteHex(151);
	public static final ByteHex $98 = new ByteHex(152);
	public static final ByteHex $99 = new ByteHex(153);
	public static final ByteHex $9a = new ByteHex(154);
	public static final ByteHex $9b = new ByteHex(155);
	public static final ByteHex $9c = new ByteHex(156);
	public static final ByteHex $9d = new ByteHex(157);
	public static final ByteHex $9e = new ByteHex(158);
	public static final ByteHex $9f = new ByteHex(159);
	public static final ByteHex $a0 = new ByteHex(160);
	public static final ByteHex $a1 = new ByteHex(161);
	public static final ByteHex $a2 = new ByteHex(162);
	public static final ByteHex $a3 = new ByteHex(163);
	public static final ByteHex $a4 = new ByteHex(164);
	public static final ByteHex $a5 = new ByteHex(165);
	public static final ByteHex $a6 = new ByteHex(166);
	public static final ByteHex $a7 = new ByteHex(167);
	public static final ByteHex $a8 = new ByteHex(168);
	public static final ByteHex $a9 = new ByteHex(169);
	public static final ByteHex $aa = new ByteHex(170);
	public static final ByteHex $ab = new ByteHex(171);
	public static final ByteHex $ac = new ByteHex(172);
	public static final ByteHex $ad = new ByteHex(173);
	public static final ByteHex $ae = new ByteHex(174);
	public static final ByteHex $af = new ByteHex(175);
	public static final ByteHex $b0 = new ByteHex(176);
	public static final ByteHex $b1 = new ByteHex(177);
	public static final ByteHex $b2 = new ByteHex(178);
	public static final ByteHex $b3 = new ByteHex(179);
	public static final ByteHex $b4 = new ByteHex(180);
	public static final ByteHex $b5 = new ByteHex(181);
	public static final ByteHex $b6 = new ByteHex(182);
	public static final ByteHex $b7 = new ByteHex(183);
	public static final ByteHex $b8 = new ByteHex(184);
	public static final ByteHex $b9 = new ByteHex(185);
	public static final ByteHex $ba = new ByteHex(186);
	public static final ByteHex $bb = new ByteHex(187);
	public static final ByteHex $bc = new ByteHex(188);
	public static final ByteHex $bd = new ByteHex(189);
	public static final ByteHex $be = new ByteHex(190);
	public static final ByteHex $bf = new ByteHex(191);
	public static final ByteHex $c0 = new ByteHex(192);
	public static final ByteHex $c1 = new ByteHex(193);
	public static final ByteHex $c2 = new ByteHex(194);
	public static final ByteHex $c3 = new ByteHex(195);
	public static final ByteHex $c4 = new ByteHex(196);
	public static final ByteHex $c5 = new ByteHex(197);
	public static final ByteHex $c6 = new ByteHex(198);
	public static final ByteHex $c7 = new ByteHex(199);
	public static final ByteHex $c8 = new ByteHex(200);
	public static final ByteHex $c9 = new ByteHex(201);
	public static final ByteHex $ca = new ByteHex(202);
	public static final ByteHex $cb = new ByteHex(203);
	public static final ByteHex $cc = new ByteHex(204);
	public static final ByteHex $cd = new ByteHex(205);
	public static final ByteHex $ce = new ByteHex(206);
	public static final ByteHex $cf = new ByteHex(207);
	public static final ByteHex $d0 = new ByteHex(208);
	public static final ByteHex $d1 = new ByteHex(209);
	public static final ByteHex $d2 = new ByteHex(210);
	public static final ByteHex $d3 = new ByteHex(211);
	public static final ByteHex $d4 = new ByteHex(212);
	public static final ByteHex $d5 = new ByteHex(213);
	public static final ByteHex $d6 = new ByteHex(214);
	public static final ByteHex $d7 = new ByteHex(215);
	public static final ByteHex $d8 = new ByteHex(216);
	public static final ByteHex $d9 = new ByteHex(217);
	public static final ByteHex $da = new ByteHex(218);
	public static final ByteHex $db = new ByteHex(219);
	public static final ByteHex $dc = new ByteHex(220);
	public static final ByteHex $dd = new ByteHex(221);
	public static final ByteHex $de = new ByteHex(222);
	public static final ByteHex $df = new ByteHex(223);
	public static final ByteHex $e0 = new ByteHex(224);
	public static final ByteHex $e1 = new ByteHex(225);
	public static final ByteHex $e2 = new ByteHex(226);
	public static final ByteHex $e3 = new ByteHex(227);
	public static final ByteHex $e4 = new ByteHex(228);
	public static final ByteHex $e5 = new ByteHex(229);
	public static final ByteHex $e6 = new ByteHex(230);
	public static final ByteHex $e7 = new ByteHex(231);
	public static final ByteHex $e8 = new ByteHex(232);
	public static final ByteHex $e9 = new ByteHex(233);
	public static final ByteHex $ea = new ByteHex(234);
	public static final ByteHex $eb = new ByteHex(235);
	public static final ByteHex $ec = new ByteHex(236);
	public static final ByteHex $ed = new ByteHex(237);
	public static final ByteHex $ee = new ByteHex(238);
	public static final ByteHex $ef = new ByteHex(239);
	public static final ByteHex $f0 = new ByteHex(240);
	public static final ByteHex $f1 = new ByteHex(241);
	public static final ByteHex $f2 = new ByteHex(242);
	public static final ByteHex $f3 = new ByteHex(243);
	public static final ByteHex $f4 = new ByteHex(244);
	public static final ByteHex $f5 = new ByteHex(245);
	public static final ByteHex $f6 = new ByteHex(246);
	public static final ByteHex $f7 = new ByteHex(247);
	public static final ByteHex $f8 = new ByteHex(248);
	public static final ByteHex $f9 = new ByteHex(249);
	public static final ByteHex $fa = new ByteHex(250);
	public static final ByteHex $fb = new ByteHex(251);
	public static final ByteHex $fc = new ByteHex(252);
	public static final ByteHex $fd = new ByteHex(253);
	public static final ByteHex $fe = new ByteHex(254);
	public static final ByteHex $ff = new ByteHex(255);

	private int value;

	private ByteHex(int value) {
		this.value = value;
	}

	@Override
	public Byte getValue() {
		return (byte) value;
	}
}
